[package]
name = "leasebook"
version = "1.0.0"
description = "A Tauri App"
authors = ["Brian Blankenship"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "leasebook_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2"
calamine = { version = "0.34.0", features = ["chrono"] }
chrono = { version = "0.4.44", features = ["serde"] }
tauri-plugin-sql = { version = "2.3.2", features = ["sqlite"] }
diesel = { version = "2.3.8", features = ["r2d2", "returning_clauses_for_sqlite_3_35", "sqlite"] }
diesel_migrations = "2.3"
dotenvy = { version = "0.15.7", features = ["cli"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
argon2 = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
webauthn-rs = "0.5.5"

[dev-dependencies]
rust_xlsxwriter = "0.94.0"
